import { NAVIGATION } from "./routes";

export const PLAYERS = [
  {
    name: "Alice",
    points: 42,
    isActive: false,
    isGK: true,
    isDEF: false,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Bob",
    points: 67,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Charlie",
    points: 18,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "David",
    points: 93,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Eve",
    points: 55,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Frank",
    points: 30,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Grace",
    points: 82,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Hank",
    points: 63,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Ivy",
    points: 77,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Jack",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "naresh",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Ethan",
    points: 42,
    isActive: false,
    isGK: true,
    isDEF: false,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Diana",
    points: 67,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Chris",
    points: 18,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Bella",
    points: 93,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Aaron",
    points: 55,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Zoe",
    points: 30,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Yara",
    points: 82,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Xander",
    points: 63,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Walter",
    points: 77,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Violet",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
  {
    name: "Uma",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
    selectedCaptain: false,
    selectedViceCaptain: false,
  },
];

export const dashboardCards = [
  {
    name: "ADD PLAYER",
    navigation: NAVIGATION.ADD_PLAYER,
  },
  {
    name: "ADD TEAM",
    navigation: NAVIGATION.ADD_TEAM,
  },
  {
    name: "TOURNAMENT",
    navigation: NAVIGATION.CREATE_TOURNAMENT,
  },
  {
    name: "ALL USERS",
    navigation: NAVIGATION.ALL_USERS,
  },
];
